services:
  - type: web
    name: scraper-service
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python ./schedular_run/schedule_run.py"
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://Gabriel:4wqUjZxSZ87Tcx0X@cluster0.nrvhn6m.mongodb.net/RealEstateDB?retryWrites=true&w=majority&appName=Cluster0"
    ports:
      - port: 8000

  - type: cron
    name: scraper-cron
    schedule: "10 20 * * *"
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python ./schedular_run/schedule_run.py"
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://Gabriel:4wqUjZxSZ87Tcx0X@cluster0.nrvhn6m.mongodb.net/RealEstateDB?retryWrites=true&w=majority&appName=Cluster0"

  - type: worker
    name: scraper-worker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python ./schedular_run/schedule_run.py"
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://Gabriel:4wqUjZxSZ87Tcx0X@cluster0.nrvhn6m.mongodb.net/RealEstateDB?retryWrites=true&w=majority&appName=Cluster0"