services:
  - type: worker
    name: scraper-worker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python ./schedular_run/schedule_run.py"
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://Gabriel:4wqUjZxSZ87Tcx0X@cluster0.nrvhn6m.mongodb.net/RealEstateDB?retryWrites=true&w=majority&appName=Cluster0"
