services:
  - type: web
    name: scrapy-scheduler
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python schedule_script.py"
    plan: free
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://Gabriel:4wqUjZxSZ87Tcx0X@cluster0.nrvhn6m.mongodb.net/RealEstateDB?retryWrites=true&w=majority&appName=Cluster0" # Replace with your MongoDB URI

  - type: cron
    name: scrapy-cron
    runtime: python
    plan: free
    schedule: "0 8 * * *"  # Runs daily at 10:50 AM GMT+3
    startCommand: "python schedule_script.py"
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://Gabriel:4wqUjZxSZ87Tcx0X@cluster0.nrvhn6m.mongodb.net/RealEstateDB?retryWrites=true&w=majority&appName=Cluster0" # Replace with your MongoDB URI
      - key: RENDER_CRON
        value: "true"